tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "inverse-primary": "#cec5be",
                "secondary": "#5d5661ff",
                "primary-fixed-dim": "#cec5be",
                "on-secondary-container": "#5a655f",
                "on-error": "#ffffff",
                "on-error-container": "#93000a",
                "surface-container-low": "#fcf2eb",
                "on-secondary-fixed-variant": "#3f4944",
                "on-secondary-fixed": "#141e19",
                "secondary-container": "#d7e2db",
                "background": "#fff8f4",
                "on-tertiary-fixed": "#1a1c1c",
                "on-surface-variant": "#4c4640",
                "primary-container": "#5c5651",
                "outline": "#7e766f",
                "surface-container-lowest": "#ffffff",
                "surface-container-high": "#f0e6e0",
                "on-primary": "#ffffff",
                "error-container": "#ffdad6",
                "inverse-surface": "#34302b",
                "on-secondary": "#ffffff",
                "on-primary-fixed": "#1f1b17",
                "error": "#ba1a1a",
                "primary-fixed": "#eae1da",
                "surface-variant": "#eae1da",
                "secondary-fixed": "#dae5de",
                "tertiary-container": "#565757",
                "surface-container-highest": "#eae1da",
                "surface-container": "#f6ece5",
                "secondary-fixed-dim": "#bec9c2",
                "tertiary-fixed-dim": "#c7c6c6",
                "surface": "#fff8f4",
                "on-background": "#1f1b17",
                "on-primary-fixed-variant": "#4b4641",
                "surface-bright": "#fff8f4",
                "surface-dim": "#e2d8d2",
                "on-tertiary-container": "#cdcdcd",
                "on-tertiary-fixed-variant": "#464747",
                "on-primary-container": "#d5ccc5",
                "surface-tint": "#635d58",
                "primary": "#443f3a",
                "tertiary": "#3f4040",
                "on-surface": "#1f1b17",
                "inverse-on-surface": "#f9efe8",
                "on-tertiary": "#ffffff",
                "tertiary-fixed": "#e3e2e2",
                "outline-variant": "#cfc5bd"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "fontFamily": {
                "headline": ["Manrope"],
                "body": ["Inter"],
                "label": ["Inter"]
            }
        },
    },
}
